#!/usr/bin/env bash
# 模组管理：按存档维护 mods.txt，启动时汇总下载并启用
# 编码: UTF-8

cluster_mods_file() { echo "$(cluster_dir "$1")/mods.txt"; }

_mod_ids_from_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  awk '
    {
      sub(/\r/, "")
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", $0)
      if ($0 ~ /^#/ || $0=="") next
      if ($0 ~ /^[0-9]+$/) print $0
      else if ($0 ~ /^workshop-[0-9]+$/) { sub(/^workshop-/, ""); print }
    }
  ' "$f"
}

all_mod_ids() {
  local name f
  while IFS= read -r name; do
    f="$(cluster_mods_file "$name")"
    _mod_ids_from_file "$f"
  done < <(list_cluster_names)
}

rebuild_global_mod_setup() {
  require_game
  ensure_dir "${GAME_DIR}/mods"
  local dest="${GAME_DIR}/mods/dedicated_server_mods_setup.lua"
  {
    echo "-- generated by dstctl $(now)"
    echo "-- 由所有存档的 mods.txt 汇总，请勿手改"
    local id
    all_mod_ids | sort -u | while read -r id; do
      [[ -n "$id" ]] && printf 'ServerModSetup("%s")\n' "$id"
    done
  } >"$dest"
  log_info "已重建 dedicated_server_mods_setup.lua"
}

write_modoverrides() {
  local name="$1"
  require_cluster "$name"
  local ids id entries=""
  ids="$(_mod_ids_from_file "$(cluster_mods_file "$name")")"
  if [[ -z "$ids" ]]; then
    entries=""
  else
    while read -r id; do
      [[ -n "$id" ]] || continue
      entries+=$(printf '  ["workshop-%s"] = { enabled = true },\n' "$id")
    done <<<"$ids"
  fi
  printf 'return {\n%s}\n' "$entries" >"$(shard_dir "$name" Master)/modoverrides.lua"
  if cluster_has_caves "$name"; then
    printf 'return {\n%s}\n' "$entries" >"$(shard_dir "$name" Caves)/modoverrides.lua"
  fi
}

# 从 modoverrides.lua 收集工坊 ID，写回 mods.txt（不覆盖 lua 里的配置）
import_mods_from_overrides() {
  local name="$1"
  require_cluster "$name"
  local file lua id n=0
  file="$(cluster_mods_file "$name")"
  [[ -f "$file" ]] || printf '# 每行一个 Steam 创意工坊模组 ID\n' >"$file"
  for lua in "$(shard_dir "$name" Master)/modoverrides.lua" "$(shard_dir "$name" Caves)/modoverrides.lua"; do
    [[ -f "$lua" ]] || continue
    while IFS= read -r id; do
      [[ -n "$id" ]] || continue
      if ! list_has "$file" "$id"; then
        list_add "$file" "$id"
        n=$((n + 1))
      fi
    done < <(grep -oE 'workshop-[0-9]+' "$lua" 2>/dev/null | sed 's/^workshop-//' | sort -u)
  done
  if (( n > 0 )); then
    log_info "已从 modoverrides.lua 同步 ${n} 个模组 ID 到 mods.txt"
  fi
}

# 开服前：lua → mods.txt；若还没有 lua 才按 mods.txt 生成
prepare_cluster_mods() {
  local name="$1"
  import_mods_from_overrides "$name"
  local master_lua caves_lua
  master_lua="$(shard_dir "$name" Master)/modoverrides.lua"
  caves_lua="$(shard_dir "$name" Caves)/modoverrides.lua"
  if [[ ! -f "$master_lua" ]]; then
    write_modoverrides "$name"
  elif cluster_has_caves "$name" && [[ ! -f "$caves_lua" ]]; then
    cp -f "$master_lua" "$caves_lua"
    log_info "已将 Master/modoverrides.lua 复制到洞穴"
  fi
  rebuild_global_mod_setup
}

cmd_mods() {
  local name="${1-}" action="${2-}"
  if [[ -z "$name" || "$name" == "sync" ]]; then
    if [[ "$name" == "sync" || "$action" == "sync" || "$1" == "--all" ]]; then
      rebuild_global_mod_setup
      local c
      while IFS= read -r c; do
        [[ -n "$c" ]] || continue
        write_modoverrides "$c"
        log_ok "已同步存档模组: $c"
      done < <(list_cluster_names)
      return 0
    fi
    die "用法: dstctl mods <存档> [list|add|remove|sync|pull] [工坊ID...]"
  fi
  require_cluster "$name"
  local file
  file="$(cluster_mods_file "$name")"
  [[ -f "$file" ]] || printf '# 每行一个 Steam 创意工坊模组 ID\n' >"$file"
  case "${action:-list}" in
    list|"")
      echo "存档 $name 模组:"
      list_show "$file"
      ;;
    add)
      shift 2
      local id n=0
      for id in "$@"; do
        id="${id#workshop-}"
        [[ "$id" =~ ^[0-9]+$ ]] || { log_warn "跳过非法 ID: $id"; continue; }
        list_add "$file" "$id"
        n=$((n + 1))
      done
      write_modoverrides "$name"
      rebuild_global_mod_setup
      log_ok "已添加 $n 个模组（启动时会自动下载/更新）"
      ;;
    remove|rm|del)
      shift 2
      local id
      for id in "$@"; do
        id="${id#workshop-}"
        list_remove "$file" "$id"
      done
      write_modoverrides "$name"
      rebuild_global_mod_setup
      log_ok "已移除模组"
      ;;
    sync)
      write_modoverrides "$name"
      rebuild_global_mod_setup
      log_ok "已按 mods.txt 覆盖写入 modoverrides.lua"
      ;;
    pull|from-lua|import-overrides)
      import_mods_from_overrides "$name"
      rebuild_global_mod_setup
      log_ok "已从 modoverrides.lua 更新 mods.txt"
      ;;
    import)
      local src="${3-}"
      [[ -f "$src" ]] || die "找不到文件: $src"
      cat "$src" >>"$file"
      write_modoverrides "$name"
      rebuild_global_mod_setup
      log_ok "已从 $src 导入"
      ;;
    *) die "未知动作: $action" ;;
  esac
}

_mod_update_new_text() {
  local logf="$1" slog="$2" slog_off="${3:-0}"
  [[ -f "$logf" ]] && cat "$logf"
  if [[ -n "$slog" && -f "$slog" ]]; then
    tail -c +"$((slog_off + 1))" "$slog" 2>/dev/null || true
  fi
}

_mod_update_log_done() {
  _mod_update_new_text "$@" | grep -qE 'FinishDownloadingServerMods|Collecting garbage|Shutting down|lua shut down|DownloadMods complete'
}

_mod_update_log_progress() {
  _mod_update_new_text "$@" | grep -qE 'Workshop|DownloadMods|OnDownloadPublishedFile'
}

update_server_mods() {
  local name="$1"
  require_game
  require_cluster "$name"
  prepare_cluster_mods "$name"
  log_info "正在更新存档 $name 使用的创意工坊模组..."
  ensure_dir "$DSTCTL_LOG_DIR"
  local logf="${DSTCTL_LOG_DIR}/modupdate-${name}-$(now_id).log"
  local slog
  slog="$(shard_log "$name" Master)"
  local slog_off=0
  [[ -f "$slog" ]] && slog_off="$(wc -c <"$slog" 2>/dev/null | tr -d ' ')"
  slog_off="${slog_off:-0}"
  local timeout_sec="${MOD_UPDATE_TIMEOUT:-600}"
  : >"$logf"

  (
    cd "$DST_BIN_DIR" || exit 1
    export LD_LIBRARY_PATH="${DST_BIN_DIR}:${DST_BIN_DIR}/lib64:${DST_BIN_DIR}/lib32:${LD_LIBRARY_PATH:-}"
    exec </dev/null
    exec "$DST_BIN" \
      -persistent_storage_root "$KLEI_ROOT" \
      -conf_dir "$CONF_DIR" \
      -cluster "$name" \
      -shard Master \
      -ugc_directory "$UGC_DIR" \
      -only_update_server_mods
  ) >"$logf" 2>&1 &
  local pid=$!
  log_info "模组更新进程 pid=${pid}，超时 ${timeout_sec}s"

  local waited=0 rc=0 saw_done=0 last_size=0 idle=0
  while kill -0 "$pid" 2>/dev/null; do
    local sz=0 slog_now=0
    sz="$(wc -c <"$logf" 2>/dev/null | tr -d ' ')"
    sz="${sz:-0}"
    if [[ -f "$slog" ]]; then
      slog_now="$(wc -c <"$slog" 2>/dev/null | tr -d ' ')"
      slog_now="${slog_now:-0}"
      if (( slog_now > slog_off )); then
        sz=$((sz + slog_now - slog_off))
      fi
    fi
    if [[ "$sz" == "$last_size" ]]; then
      idle=$((idle + 2))
    else
      idle=0
      last_size="$sz"
    fi

    if _mod_update_log_done "$logf" "$slog" "$slog_off"; then
      saw_done=1
      sleep 2
      if kill -0 "$pid" 2>/dev/null; then
        kill -TERM "$pid" 2>/dev/null || true
        sleep 2
        kill -KILL "$pid" 2>/dev/null || true
      fi
      break
    fi

    if _mod_update_log_progress "$logf" "$slog" "$slog_off" && (( idle >= 20 )); then
      saw_done=1
      log_info "模组更新已无新输出，结束更新进程"
      kill -TERM "$pid" 2>/dev/null || true
      sleep 2
      kill -KILL "$pid" 2>/dev/null || true
      break
    fi

    if (( waited > 0 && waited % 10 == 0 )); then
      local last=""
      last="$(tail -n 1 "$logf" 2>/dev/null | tr -d '\r')"
      if [[ -z "$last" && -f "$slog" ]]; then
        last="$(tail -n 1 "$slog" 2>/dev/null | tr -d '\r')"
      fi
      log_info "模组更新中... ${last:-等待 Steam 响应}"
    fi

    if (( waited >= timeout_sec )); then
      log_warn "模组更新超时，结束进程。日志: $logf"
      kill -TERM "$pid" 2>/dev/null || true
      sleep 2
      kill -KILL "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      drain_stdin
      return 1
    fi
    sleep 2
    waited=$((waited + 2))
  done
  wait "$pid" 2>/dev/null || rc=$?
  drain_stdin

  if _mod_update_new_text "$logf" "$slog" "$slog_off" | grep -qE 'ODPF failed entirely'; then
    log_warn "模组下载可能失败，尝试修复 steamclient.so 后重试"
    dstctl_fix_steamclient
  fi
  if _mod_update_new_text "$logf" "$slog" "$slog_off" | grep -qE 'E_EXPIRED_TOKEN|Failed to authenticate|Account Failed'; then
    log_warn "认证失败，模组可能未更新完整，详见 $logf"
    return 1
  fi
  if (( rc != 0 && rc != 143 && rc != 137 && saw_done == 0 )); then
    if [[ ! -s "$logf" ]]; then
      log_warn "模组更新进程返回 ${rc} 且无日志"
      return 1
    fi
    log_warn "模组更新进程返回 ${rc}，详见 $logf"
  fi
  log_ok "模组更新完成"
  return 0
}
